*** /home/draje/Code/gzdoom/src/actorptrselect.h	2017-06-18 07:52:50.683013539 -0400
--- /home/draje/Code/GitHub/nvllsvm/GZDoom-Android/doom/src/main/jni/gzdoom21_pre/src/actorptrselect.h	2017-06-18 09:09:24.161730580 -0400
***************
*** 36,47 ****
  	AAPTR_PLAYER8 = 0x2000,
  
  	AAPTR_FRIENDPLAYER = 0x4000,
  
  	AAPTR_PLAYER_SELECTORS =
  		AAPTR_PLAYER_GETTARGET|AAPTR_PLAYER_GETCONVERSATION,
  
  	AAPTR_GENERAL_SELECTORS =
! 		AAPTR_TARGET|AAPTR_MASTER|AAPTR_TRACER|AAPTR_FRIENDPLAYER,
  
  	AAPTR_STATIC_SELECTORS =
  		AAPTR_PLAYER1|AAPTR_PLAYER2|AAPTR_PLAYER3|AAPTR_PLAYER4|
--- 36,48 ----
  	AAPTR_PLAYER8 = 0x2000,
  
  	AAPTR_FRIENDPLAYER = 0x4000,
+ 	AAPTR_GET_LINETARGET = 0x8000,
  
  	AAPTR_PLAYER_SELECTORS =
  		AAPTR_PLAYER_GETTARGET|AAPTR_PLAYER_GETCONVERSATION,
  
  	AAPTR_GENERAL_SELECTORS =
! 		AAPTR_TARGET|AAPTR_MASTER|AAPTR_TRACER|AAPTR_FRIENDPLAYER|AAPTR_GET_LINETARGET,
  
  	AAPTR_STATIC_SELECTORS =
  		AAPTR_PLAYER1|AAPTR_PLAYER2|AAPTR_PLAYER3|AAPTR_PLAYER4|
